### Ex1 (Risoluzione Overloading):
**Chiamata (a)**
- Candidate: #4
- Utilizzabili: #4
- Migliore: #4

**Chiamata (b)**
- Candidate: #4, #7
- Utilizzabili: #4
- Migliore: #4

**Chiamata (c)**
- Candidate: #1, #2
- Utilizzabili: #1, #2
- Migliore: #1

**Chiamata (d)**
- Candidate: #1, #2, #5
- Utilizzabili: #1, #2, #5
- Migliore: #5

**Chiamata (e)**
- Candidate: #1, #2
- Utilizzabili: #1, #2
- Migliore: ambiguous (errore di compilazione)

**Chiamata (f)**
- Candidate: #1, #2, #5
- Utilizzabili: #2
- Migliore: #2

**Chiamata (g)**
- Candidate: #3
- Utilizzabili: #3
- Migliore: #3

**Chiamata (h)**
- Candidate: #3, #6
- Utilizzabili: #3, #6
- Migliore: #6

### Ex5 (Gestione Risorse):
Problemi:
1. Se l'inizializzazione di `s` o di `pd` fallisce la risorsa `pi` non viene liberata poiché l'oggetto di tipo `A` non è ancora in uno stato consistente
2. Non ne ho idea...?

```c++
//Possibile soluzione
#include <string>
class A {
	int* pi;
	std::string str;
	double* pd;
public:
	A(const std::string& s) : str(s) {
		pi = new int;
		try {
			pd = new double;
		} catch(...) {
			delete pi;
			throw;
		}
	}
	~A() {
		delete pi;
		delete pd;
	}
}
```
Giustificazione: Dopo l'allocazione di una delle 2 risorse di memoria dinamiche viene aperto un blocco try catch in modo da catturare qualsiasi eccezione avvenga durante l'allocazione della seconda delle 2 risorse, e nel caso venga catturata rilasciare la prima risorsa tramite delete
